version: '3.7'

services:

  tn-backend:
    container_name: tn-backend
    image: tn/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    ports:
      - '4000:4000'
    restart: always

  tn-frontend:
    container_name: tn-frontend
    image: tn/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - ./frontend/.env
    ports:
      - '3000:3000'
    depends_on:
      - tn-backend
    restart: always

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    command: --quiet